import type { BoardTask } from './types';

const hourAgo = new Date(Date.now() - 3600_000).toISOString();
const dayAgo = new Date(Date.now() - 86400_000).toISOString();

export const defaultTasks: BoardTask[] = [
  {
    id: 'task-001',
    title: 'Analyze customer support tickets for recurring issues',
    description: 'Review last 30 days of support tickets and identify top 5 recurring patterns.',
    status: 'in_progress',
    priority: 'high',
    labels: ['analytics', 'support'],
    assignee: { id: 'research', type: 'agent', name: 'RESEARCH', color: '#ce93d8' },
    creatorId: 'user-1',
    creatorType: 'human',
    progress: 65,
    comments: [
      {
        id: 'c-001',
        taskId: 'task-001',
        authorId: 'research',
        authorType: 'agent',
        authorName: 'RESEARCH',
        content: 'Found 3 major patterns so far: billing confusion, onboarding friction, and API rate limit complaints.',
        createdAt: hourAgo,
      },
    ],
    activity: [
      { id: 'a-001', taskId: 'task-001', actorId: 'user-1', actorType: 'human', actorName: 'You', action: 'created', timestamp: dayAgo },
      { id: 'a-002', taskId: 'task-001', actorId: 'research', actorType: 'agent', actorName: 'RESEARCH', action: 'status_changed', detail: 'todo → in_progress', timestamp: dayAgo },
      { id: 'a-003', taskId: 'task-001', actorId: 'research', actorType: 'agent', actorName: 'RESEARCH', action: 'progress_updated', detail: '0% → 65%', timestamp: hourAgo },
      { id: 'a-004', taskId: 'task-001', actorId: 'research', actorType: 'agent', actorName: 'RESEARCH', action: 'commented', timestamp: hourAgo },
    ],
    createdAt: dayAgo,
    updatedAt: hourAgo,
  },
  {
    id: 'task-002',
    title: 'Draft weekly growth report',
    description: 'Compile metrics from all channels and prepare executive summary.',
    status: 'todo',
    priority: 'medium',
    labels: ['report', 'growth'],
    assignee: { id: 'growth', type: 'agent', name: 'GROWTH', color: '#81c784' },
    creatorId: 'user-1',
    creatorType: 'human',
    progress: 0,
    comments: [],
    activity: [
      { id: 'a-005', taskId: 'task-002', actorId: 'user-1', actorType: 'human', actorName: 'You', action: 'created', timestamp: hourAgo },
      { id: 'a-006', taskId: 'task-002', actorId: 'user-1', actorType: 'human', actorName: 'You', action: 'assigned', detail: 'Assigned to GROWTH', timestamp: hourAgo },
    ],
    createdAt: hourAgo,
    updatedAt: hourAgo,
  },
  {
    id: 'task-003',
    title: 'Review invoice processing pipeline',
    description: 'Check for bottlenecks in the automated invoice workflow and suggest optimizations.',
    status: 'review',
    priority: 'high',
    labels: ['erp', 'optimization'],
    assignee: { id: 'user-1', type: 'human', name: 'You' },
    creatorId: 'ops',
    creatorType: 'agent',
    progress: 100,
    comments: [
      {
        id: 'c-002',
        taskId: 'task-003',
        authorId: 'ops',
        authorType: 'agent',
        authorName: 'OPS',
        content: 'Analysis complete. Found 2 bottlenecks: PDF parsing takes 4s avg, and tax calculation hits rate limits during batch runs.',
        createdAt: hourAgo,
      },
    ],
    activity: [
      { id: 'a-007', taskId: 'task-003', actorId: 'ops', actorType: 'agent', actorName: 'OPS', action: 'created', timestamp: dayAgo },
      { id: 'a-008', taskId: 'task-003', actorId: 'ops', actorType: 'agent', actorName: 'OPS', action: 'completed', timestamp: hourAgo },
      { id: 'a-009', taskId: 'task-003', actorId: 'ops', actorType: 'agent', actorName: 'OPS', action: 'status_changed', detail: 'in_progress → review', timestamp: hourAgo },
    ],
    agentTaskRef: 'at-003',
    createdAt: dayAgo,
    updatedAt: hourAgo,
  },
  {
    id: 'task-004',
    title: 'Set up Slack integration for customer alerts',
    status: 'backlog',
    priority: 'low',
    labels: ['integration', 'slack'],
    creatorId: 'user-1',
    creatorType: 'human',
    progress: 0,
    comments: [],
    activity: [
      { id: 'a-010', taskId: 'task-004', actorId: 'user-1', actorType: 'human', actorName: 'You', action: 'created', timestamp: dayAgo },
    ],
    createdAt: dayAgo,
    updatedAt: dayAgo,
  },
  {
    id: 'task-005',
    title: 'Monitor security scan results',
    description: 'SENTINEL completed the daily security scan. Review flagged items.',
    status: 'done',
    priority: 'critical',
    labels: ['security'],
    assignee: { id: 'sentinel', type: 'agent', name: 'SENTINEL', color: '#ef5350' },
    creatorId: 'sentinel',
    creatorType: 'agent',
    progress: 100,
    comments: [],
    activity: [
      { id: 'a-011', taskId: 'task-005', actorId: 'sentinel', actorType: 'agent', actorName: 'SENTINEL', action: 'created', timestamp: dayAgo },
      { id: 'a-012', taskId: 'task-005', actorId: 'sentinel', actorType: 'agent', actorName: 'SENTINEL', action: 'completed', timestamp: dayAgo },
    ],
    agentTaskRef: 'at-005',
    createdAt: dayAgo,
    updatedAt: dayAgo,
    completedAt: dayAgo,
  },
];
