import {
  Controller,
  Post,
  Body,
  Headers,
  HttpCode,
  Logger,
  ForbiddenException,
  BadRequestException,
  UseGuards,
} from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { Public } from '../auth/decorators/public.decorator';
import { LicenseGuard } from '../license/guards/license.guard';
import { ProFeatureRequired } from '../license/decorators/pro-feature.decorator';
import { InboundRouterService } from './inbound-router.service';

/**
 * Payload sent by the UniCore web chat widget.
 *
 * The widget embeds on any website and sends messages here;
 * agents reply via the OpenClaw pipeline which pushes responses
 * back over the widget's own WebSocket connection.
 */
interface WebchatMessageBody {
  /** Stable session identifier generated by the widget (e.g. UUID). */
  sessionId: string;
  /** The visitor's typed message. */
  message: string;
  /** Optional display name provided by the visitor or the host page. */
  senderName?: string;
  /** Optional context passed from the host page (URL, user data, etc.). */
  metadata?: Record<string, unknown>;
}

@Controller('webhooks/webchat')
@ProFeatureRequired('allChannels')
@UseGuards(LicenseGuard)
export class WebchatWebhookController {
  private readonly logger = new Logger(WebchatWebhookController.name);

  constructor(
    private readonly config: ConfigService,
    private readonly inboundRouter: InboundRouterService,
  ) {}

  /**
   * Receives messages from the UniCore web chat widget.
   *
   * Authentication: token-based via X-Webchat-Token header.
   * Set WEBCHAT_WIDGET_TOKEN in env to enable token validation.
   * When unset, all requests are accepted (useful for open public widgets).
   *
   * @Public — no JWT; the widget calls this without a user session
   */
  @Public()
  @Post()
  @HttpCode(200)
  async handleMessage(
    @Body() body: WebchatMessageBody,
    @Headers('x-webchat-token') token?: string,
  ): Promise<{ ok: true }> {
    const expectedToken = this.config.get<string>('WEBCHAT_WIDGET_TOKEN');
    if (expectedToken && token !== expectedToken) {
      this.logger.warn(
        `Webchat webhook received with invalid token (sessionId=${body.sessionId ?? 'unknown'})`,
      );
      throw new ForbiddenException('Invalid webchat token');
    }

    if (!body.sessionId || !body.message) {
      throw new BadRequestException('Missing required fields: sessionId, message');
    }

    const shortSession = body.sessionId.slice(0, 8);
    const senderName = body.senderName ?? `Web User (${shortSession})`;

    this.logger.log(
      `Webchat message received: sessionId=${body.sessionId}, text="${body.message}"`,
    );

    await this.inboundRouter.route({
      channel: 'webchat',
      senderId: body.sessionId,
      senderName,
      text: body.message,
      rawPayload: body as unknown as Record<string, unknown>,
      metadata: body.metadata,
    });

    return { ok: true };
  }
}
