import type { BackofficeAgent } from './types';

export const defaultAgents: BackofficeAgent[] = [
  {
    id: 'router',
    name: 'ROUTER',
    role: 'System Orchestrator',
    status: 'working',
    room: 'main-office',
    activity: 'Routing messages across channels...',
    color: '#00e5ff',
    deskItems: ['triple-monitor', 'server-rack'],
  },
  {
    id: 'comms',
    name: 'COMMS',
    role: 'Communications Agent',
    status: 'working',
    room: 'standalone',
    activity: 'Handling LINE & Facebook messages...',
    color: '#4fc3f7',
    deskItems: ['monitors', 'headset'],
  },
  {
    id: 'finance',
    name: 'FINANCE',
    role: 'Finance Agent',
    status: 'working',
    room: 'standalone',
    activity: 'Processing invoices...',
    color: '#81c784',
    deskItems: ['monitors', 'charts'],
  },
  {
    id: 'growth',
    name: 'GROWTH',
    role: 'Growth & Marketing',
    status: 'idle',
    room: 'conference',
    activity: 'Analyzing campaign metrics...',
    color: '#ffb74d',
    deskItems: ['charts'],
  },
  {
    id: 'ops',
    name: 'OPS',
    role: 'Operations Agent',
    status: 'working',
    room: 'standalone',
    activity: 'Managing workflows...',
    color: '#ce93d8',
    deskItems: ['monitors', 'books'],
  },
  {
    id: 'research',
    name: 'RESEARCH',
    role: 'Research Agent',
    status: 'working',
    room: 'standalone',
    activity: 'Analyzing market data...',
    color: '#7c4dff',
    deskItems: ['monitor', 'galaxy-screen'],
  },
  {
    id: 'sentinel',
    name: 'SENTINEL',
    role: 'Security Monitor',
    status: 'working',
    room: 'standalone',
    activity: 'Scanning for anomalies...',
    color: '#ef5350',
    deskItems: ['alert-light', 'monitors'],
  },
  {
    id: 'builder',
    name: 'BUILDER',
    role: 'Builder Agent',
    status: 'idle',
    room: 'conference',
    activity: 'Waiting for build tasks...',
    color: '#4dd0e1',
    deskItems: ['easel', 'palette'],
  },
  {
    id: 'erp',
    name: 'ERP',
    role: 'ERP Integration',
    status: 'working',
    room: 'standalone',
    activity: 'Syncing inventory data...',
    color: '#f06292',
    deskItems: ['books', 'monitors'],
  },
];
